version: '3'
services:
  api:
    build: ./api
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/tu_basedatos
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
